ARG base_image=immersive-server-base:v1.12
FROM ${base_image} AS base

RUN cd /home/immersive/ && \
    export LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH && \
    export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH && \
    ldd Sample-Videos/ffmpeg | tr -s '[:blank:]' '\n' | grep '^/' | \
    xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;' && \
    ldd /root/WorkerServer | tr -s '[:blank:]' '\n' | grep '^/' | \
    xargs -I % sh -c 'mkdir -p $(dirname deps%); cp % deps%;'

FROM centos:7.6.1810

USER root
WORKDIR /home/immersive/
ARG WORKDIR=/home/immersive/

COPY --from=base /etc/passwd /etc/group /etc/
COPY --from=base ${WORKDIR}/Sample-Videos ${WORKDIR}/Sample-Videos
COPY --from=base ${WORKDIR}/deps/lib64 /usr/lib64
COPY --from=base ${WORKDIR}/deps/usr /usr/
COPY --from=base /usr/local/nginx /usr/local/nginx
COPY --from=base /usr/local/lib/libHevcVideoStreamProcess.so /usr/local/lib/
COPY --from=base /usr/local/lib/libHighResPlusFullLowResPacking.so /usr/local/lib/
COPY --from=base /usr/local/lib/libSegmentWriter.so /usr/local/lib/
COPY --from=base /usr/local/lib/libMPDWriter.so /usr/local/lib/
COPY --from=base /usr/lib64/libnuma.so.1.0.0 /usr/lib64/
COPY --from=base /usr/lib64/libnuma.so.1 /usr/lib64/
COPY --from=base /usr/bin/numactl /usr/bin/
COPY --from=base /usr/bin/bc /usr/bin/
COPY --from=base /usr/bin/openssl /usr/bin/
COPY --from=base /root/WorkerServer /root/

EXPOSE 443
EXPOSE 8080
